# Generated by Django 5.2.6 on 2025-10-06 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteuser'),
    ]

    operations = [
    ]
