# Generated by Django 5.2.6 on 2025-10-08 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_backfill_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_key', models.CharField(db_index=True, max_length=64)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('ua', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_events', to='core.link')),
            ],
            options={
                'verbose_name': 'Клик',
                'verbose_name_plural': 'Клики',
            },
        ),
        migrations.DeleteModel(
            name='SiteUser',
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('created_at',), 'verbose_name': 'Пользователь сайта', 'verbose_name_plural': 'Пользователи сайта'},
        ),
        migrations.AddField(
            model_name='member',
            name='is_editor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='clickevent',
            index=models.Index(fields=['link', 'user_key'], name='core_clicke_link_id_aceb8f_idx'),
        ),
        migrations.AddIndex(
            model_name='clickevent',
            index=models.Index(fields=['created_at'], name='core_clicke_created_2d536c_idx'),
        ),
    ]
